#!/usr/bin/env bash

VERSION="1.0"

## Example addon
##
## This is an example addon. It's purpose is to show sample folder structure
## and concepts of creating addons.
##
##   fin example <command>
##
## Usage:
##   hello       Display contents of 'somefile'
##   version     Display addon version


case "$1" in
	hello)
		cat "$ADDON_ROOT/some-additional-files/somefile"
		;;
	version|-v)
		echo "$VERSION"
		;;
	*)
		fin help example
		;;
esac
