#!/usr/bin/env bash

VERSION="1.0"

## Example addon
##
## This is an example addon. It's purpose is to show sample folder structure
## and concepts of creating addons.
##
##   fin example <command>
##
## Usage:
##   hello      Displays contents of 'somefile'
##   version    Display addon version. Every addon has this command automatically


case "$1" in
	hello)
		cat "$ADDON_ROOT/some-additional-files/somefile"
		;;
	*)
		fin help example
		;;
esac
