#!/usr/bin/env bash

#: exec_target = cli

## Run automated tests with SimpleTest.
##
## Usage: fin simpletest <args>

# Find the run-tests script.
if [ -f "core/scripts/run-tests.sh" ]; then
    SCRIPT_FILE="$PROJECT_ROOT/$DOCROOT/core/scripts/run-tests.sh"
else
    SCRIPT_FILE="$PROJECT_ROOT/$DOCROOT/scripts/run-tests.sh"
fi

# Execute the script.
php $SCRIPT_FILE \
  --php `which php` \
  --color \
  $@
