#!/usr/bin/env bash

die ()
{
	echo "$1"
	exit 1
}

## Generate uli

cd "$PROJECT_ROOT/$DOCROOT" || die "Could not change dir to $PROJECT_ROOT/$DOCROOT"
uli=$(fin drush uli 2>&1 | sed "s/default/$VIRTUAL_HOST/" | sed "s/http\:/https:/")
echo "$uli"
[[ "$uli" == *"Error"* ]] && exit 1

( which pbcopy >/dev/null 2>&1 ) &&
	echo "$uli" | pbcopy &&
	echo "[+] Copied to clipboard"