#!/usr/bin/env bash

VERSION="1.0.2-beta"

## Check Drupal code for deprecations and discover bugs via static analysis.
##
## Built on PHPStan, this static analysis tool will check
## for correctness, deprecation errors, and more
##
##  fin drupal-check <module_name> <options>
##

## Options
##    -a        Check analysis
##    -d        Check deprecations (default)
##    -t        Module type {core, custom, profile, contrib (default)}
##    -v        Verbose output.

# Default variables.
ROOT_DIR="/var/www/"
DRUPAL_CHECK_BINARY="/usr/local/bin/drupal-check"
COMPOSER_DIR="${PROJECT_ROOT}/vendor/bin/drupal-check"
MODULE_TYPE="contrib"
CHECK_OPTS=()
PROFILE_DIR=""
SCRIPT_ARG=""
COMPOSER="local"

# Import local settings
[[ -f local.drupal-check ]] && source local.drupal-check || CUSTOM=false
if [[ ! -f "${COMPOSER_DIR}" ]]; then
  COMPOSER=false
fi

# Check if arguments are included.
# Get the module name.
if [[ -z "$1" ]]; then
    echo "Please provide a module name."
    exit 1
else
    MODULE_NAME="$1"
    shift
fi

while getopts 'adt:p:v' opt; do
    case ${opt} in
        a )
            CHECK_OPTS+=("-a")
        ;;
        d )
            CHECK_OPTS+=("-d")
        ;;
        t )
            MODULE_TYPE=${OPTARG}
        ;;
        p )
            PROFILE_DIR=${OPTARG}
        ;;
        v )
            CHECK_OPTS+=("-vvv")
        ;;
        * )
            echo "Invalid argument."
    esac
done

# Generate the module path.
if [[ "${MODULE_TYPE}" = "core" ]]; then
    MODULE_PATH="/var/www/${DOCROOT}/${MODULE_TYPE}/modules/${MODULE_NAME}"
elif [[ "${MODULE_TYPE}" = "profile" ]]; then
  if ! [[ "${DRUPAL_CHECK_MODULE_PATH}" = false ]]; then
    MODULE_PATH="${DRUPAL_CHECK_MODULE_PATH}"
  else
    MODULE_PATH="/var/www/${DOCROOT}/profiles/custom/${PROFILE_DIR}/modules/${MODULE_NAME}"
  fi
else
    MODULE_PATH="/var/www/${DOCROOT}/modules/${MODULE_TYPE}/${MODULE_NAME}"
fi

# Execute script.
if [[ $COMPOSER = false ]]; then
  fin exec ${DRUPAL_CHECK_BINARY} ${CHECK_OPTS[@]} ${MODULE_PATH}
else
  fin exec ./vendor/bin/drupal-check ${CHECK_OPTS[@]} ${MODULE_PATH}
fi
