#!/usr/bin/env bash

docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PROJECT_ROOT" \
  --volume "$PROJECT_ROOT":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate $@
