#!/usr/bin/env bash

VERSION="1.0"

## Mkcert addon
##
## This is an mkcert addon. 
## See: https://github.com/FiloSottile/mkcert for details
## 
## It creates trusted certificates for $VIRTUAL_HOST and *.$VIRTUAL_HOST
##
##   fin mkcert <command>
##
## Usage:
##   create (cr)   Create a certificate for this project
##   version       Display addon version

CONFIG_CERTS=${CONFIG_CERTS:-$HOME/.docksal/certs}

if [[ "$TERM" != "dumb" ]]; then
	# Console colors
	red='\033[0;91m'
	red_bg='\033[101m'
	yellow_bg='\033[43m'
	lightmagenta_bg='\033[0;105m'
	green='\033[0;32m'
	green_bg='\033[42m'
	yellow='\033[0;33m'
	yellow_bold='\033[1;33m'
	blue='\033[0;34m'
	lime='\033[0;92m'
	acqua='\033[0;96m'
	magenta='\033[0;35m'
	lightmagenta='\033[0;95m'
	NC='\033[0m'
fi

echo-red ()      { echo -e "${red}$1${NC}"; }
echo-green ()    { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow ()   { echo -e "${yellow}$1${NC}"; }

echo-warning ()
{
	echo -e "${yellow_bg} WARNING: ${NC} ${yellow}$1${NC}";
	shift
	for arg in "$@"; do
		echo -e "           $arg"
	done
}

echo-error ()
{
	echo -e "${red_bg} ERROR: ${NC} ${red}$1${NC}"
	shift
	for arg in "$@"; do
		echo -e "        $arg"
	done
}

echo-alert ()
{
	echo -e "${lightmagenta_bg} ALERT: ${NC} ${lightmagenta}$1${NC}"
	shift
	for arg in "$@"; do
		echo -e "         $arg"
	done
}

# print string in $1 for $2 times
echo-repeat ()
{
    seq  -f $1 -s '' $2; echo
}

# prints message to stderr
echo-stderr ()
{
	(>&2 echo "$@")
}

# Get path to .docksal folder using upfind
get_project_path ()
{
	if [[ "$DOCKSAL_PATH" == "" ]]; then
		DOCKSAL_PATH=$(upfind ".docksal")
	fi
	# If we reached $HOME, then we did not find the project root.
	if [[ "$DOCKSAL_PATH" != "$HOME" ]]; then
		echo "$DOCKSAL_PATH"
	fi
}

# Check that .docksal is present
check_project_root ()
{
	if [[ "$(get_project_path)" == "" ]] ; then
		echo-error "Cannot detect project root." \
			"Please make sure you have ${yellow}.docksal${NC} directory in the root of your project." \
			"To setup a basic Docksal stack in the current directory run ${yellow}fin config generate${NC}"
		exit 1
	fi
}


# Check that project certificate for $VIRTUAL_HOST, else create them
create_project_certificate ()
{
	check_project_root
	if [[ ! -f "${CONFIG_CERTS}/${VIRTUAL_HOST}.crt" ]]; then
		mkcert -key-file ${CONFIG_CERTS}/${VIRTUAL_HOST}.key -cert-file ${CONFIG_CERTS}/${VIRTUAL_HOST}.crt *.${VIRTUAL_HOST} ${VIRTUAL_HOST} &>/dev/null
		if [[ $? == 0 ]]; then
		  echo-green "Created ssl certificates for ${VIRTUAL_HOST}"
		else
		  echo-red "Could not create ssl certificates. Is mkcert still installed?"
		fi
	else
		echo-green "ssl certificates for already exixts as ${CONFIG_CERTS}/${VIRTUAL_HOST}.crt"
	fi
}



case "$1" in
	create|cr)
	  create_project_certificate
	  ;;
	version|-v)
		echo "$VERSION"
		;;
	*)
		fin help mkcert
		;;
esac
