#!/usr/bin/env bash

## Enable/disable coder for current project
##
## Sub-commands:
##   enable		Enable coder
##   disable	Disable coder

# Console colors
red='\033[0;91m'
red_bg='\033[101m'
yellow_bg='\033[43;90m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[0;33m'
yellow_bold='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }
die () { echo -e "$1"; exit 1; }

DOCKSAL_YML=".docksal/docksal.yml"
DOCKSAL_YML_NEW=".docksal/docksal.yml.new"
DOCKSAL_ENV=".docksal/docksal.env"
DOCKSAL_STACKS="$HOME/.docksal/stacks"
CODER_YML="$ADDON_ROOT/conf/coder.yml"

#----------------------------------- YML & config functions ------------------------------------------

# Check whether given string is in config
# $1 - string to find
in_config ()
{
	fin config 2>/dev/null | grep "$1" >/dev/null
}

# Check that docksal.yml is valid
yml_is_valid ()
{
	[[ -f "$DOCKSAL_YML" ]] && $(cat "$DOCKSAL_YML" 2>/dev/null | grep "services" >/dev/null)
}

# Prepares stack to editing docksal.yml config
yml_prepare ()
{
	# Get yml version to use for a new file from existing stacks
	YML_VERSION=$(head "$DOCKSAL_STACKS/volumes-bind.yml" | grep "version")
	# YML_DEFAULT_BODY="${YML_VERSION}\nservices:"
	YML_DEFAULT_BODY="services:"
	NEW_STACK='DOCKSAL_STACK="default"'

	# Source docksal.env
	source "$DOCKSAL_ENV" >/dev/null 2>&1

	# If DOCKSAL_STACK is not set, then...
	if [[ -z "$DOCKSAL_STACK" ]]; then
		echo "  Configuring to use DOCKSAL_STACK=\"default\"..."
		# ...set stack to default so we could use docksal.yml
		echo -e "$NEW_STACK" >> "$DOCKSAL_ENV"
	fi

	# Create docksal.yml if needed
	yml_is_valid || echo -e "$YML_DEFAULT_BODY" >> "$DOCKSAL_YML"
}

# Install tool required to edit yml from command line
yml_install_tools ()
{
	fin exec "which yaml >/dev/null 2>&1 || npm install --silent -g yaml-cli >/dev/null"
}

# Add a service to docksal.yml from another yml
# $1 - filename of yml get service from
yml_add_service ()
{
	[[ -z "$1" ]] && echo "File not found: $1" && return 1
	# TODO: use https://www.npmjs.com/package/merge-yaml
	cat "$1" >> "$DOCKSAL_YML"
}

# Removes a service from docksal.yml
# $1 - service name
yml_remove_service ()
{
	[[ -z "$1" ]] && echo "Provide a service name to remove" && return 1
	local service="$1"
	read -r -d '' CODE_TO_EXEC <<-EOF
		yaml set $DOCKSAL_YML services.$service | grep -v '$service:' | tee $DOCKSAL_YML_NEW >/dev/null;
		[[ -z "\$(yaml get $DOCKSAL_YML_NEW services)" ]] && rm '$DOCKSAL_YML' || mv $DOCKSAL_YML_NEW $DOCKSAL_YML
	EOF
	# Remove service. If no services left after that, then remove docksal.yml
	fin exec "$CODE_TO_EXEC"
}

#-------------------------------------- coder functions ---------------------------------------------

# Enable container and settings
coder_enable ()
{
	# Check that coder is not already enabled
	if (in_config "image: acondura/code-server"); then
		echo "  Coder support is already enabled." && exit
	fi

	echo "  Enabling coder..."
	yml_prepare
	# Add coder service to docksal.yml
	yml_add_service "$CODER_YML"
	# Apply stack changes.
	fin stop cli
	fin up

  if [[ $VIRTUAL_HOST == *"docksal" ]]; then
    echo "  Generating Coder URL..."
    VHOST=$(fin config | grep -m 1 VIRTUAL_HOST: | awk '{ print $2 }')
    echo-green "Coder UI:${yellow} http://ide-$VHOST${NC}"
  else
    echo "  Generating Coder URL and password..."
    CODER_PASS=$(fin logs coder | grep Password | tail -1 | awk '{ print $5 }')
    VHOST=$(fin config | grep -m 1 VIRTUAL_HOST: | awk '{ print $2 }')
    echo-green "Coder UI:${yellow} http://ide-$VHOST${NC}, password: $CODER_PASS"
  fi
}

# Disable container and settings
coder_disable ()
{
	echo "  Running checks..."
	# Make sure cli container is running
	if ! (fin ps | grep "_cli_" | grep "Up" >/dev/null); then
		echo "  ERROR: Start the project with fin start first" && exit 1
	fi

	# Make sure coder is installed
	if ! in_config "image: acondura/code-server"; then
		echo "  Coder support is not enabled at the moment." && exit
	fi

	echo "  Preparing to remove coder service..."
	yml_install_tools
	# Remove coder service from docksal.yml
	yml_remove_service "coder"
	# Apply stack changes
	COMPOSE_FILE="" fin stop cli
	fin up
}

# Get coder password
coder_getpass ()
{
	echo "  Running checks..."
	# Make sure cli container is running
	if ! (fin ps | grep "_cli_" | grep "Up" >/dev/null); then
		echo "  ERROR: Start the project with fin start first" && exit 1
	fi

	# Make sure coder is installed
	if ! in_config "image: acondura/code-server"; then
		echo "  Coder support is not enabled at the moment." && exit
	fi

	echo "  Generating Coder URL and password..."
  CODER_PASS=$(fin logs coder | grep Password | tail -1 | awk '{ print $5 }')
  VHOST=$(fin config | grep -m 1 VIRTUAL_HOST: | awk '{ print $2 }')
  echo-green "Coder UI:${yellow} http://ide-$VHOST${NC}, password: $CODER_PASS"
}

#------------------------------------------ Runtime -----------------------------------------------

cd "$PROJECT_ROOT"

case "$1" in
	enable)
		coder_enable
		;;
	disable)
		coder_disable
		;;
	restart)
		coder_disable
		coder_enable
		;;
	getpass)
		coder_getpass
		;;
	*)
		echo "Usage: fin coder <enable|disable|restart|getpass>"
		exit 1
		;;
esac
